UPDATE public.foods SET icon = '🥜' WHERE name = 'Almendra Cruda';
UPDATE public.foods SET icon = '🍚' WHERE name = 'Arroz' AND brand = 'SOS';
UPDATE public.foods SET icon = '🍚' WHERE name = 'Arroz Integral';
UPDATE public.foods SET icon = '🍚' WHERE name = 'Arroz Redondo' AND brand = 'Alipende';
UPDATE public.foods SET icon = '🍚' WHERE name = 'Arroz Redondo' AND brand = 'Hacendado';
UPDATE public.foods SET icon = '🐟' WHERE name = 'Atún al natural';
UPDATE public.foods SET icon = '🌾' WHERE name = 'Avena Integral';
UPDATE public.foods SET icon = '🍯' WHERE name = 'Barbacoa Miel';
UPDATE public.foods SET icon = '🍫' WHERE name = 'Cacao' AND brand = 'La Chocolatera';
UPDATE public.foods SET icon = '🍫' WHERE name = 'Cacao' AND brand = 'Valor';
UPDATE public.foods SET icon = '🍜' WHERE name = 'Caldo de Pollo' AND brand = 'Alipende';
UPDATE public.foods SET icon = '🍜' WHERE name = 'Caldo de Pollo' AND brand = 'Día';
UPDATE public.foods SET icon = '🍜' WHERE name = 'Caldo de Pollo' AND brand = 'Gallina Blanca';
UPDATE public.foods SET icon = '🥣' WHERE name = 'Cereales de Arroz';
UPDATE public.foods SET icon = '🥣' WHERE name = 'Cereales Veganos';
UPDATE public.foods SET icon = '🍫' WHERE name = 'Chocolate 85%';
UPDATE public.foods SET icon = '🥚' WHERE name = 'Claras de Huevo';
UPDATE public.foods SET icon = '🥣' WHERE name = 'Corn Flakes';
UPDATE public.foods SET icon = '🥜' WHERE name = 'Crema de cacahuete Crunchy';
UPDATE public.foods SET icon = '🥣' WHERE name = 'Crema de Calabacin';
UPDATE public.foods SET icon = '🌿' WHERE name = 'Esparragos';
UPDATE public.foods SET icon = '🍝' WHERE name = 'Fideos';
UPDATE public.foods SET icon = '🥖' WHERE name = 'Fuet Espetec';
UPDATE public.foods SET icon = '🍪' WHERE name = 'Galleta con Vainilla';
UPDATE public.foods SET icon = '🥘' WHERE name = 'Garbanzos';
UPDATE public.foods SET icon = '🍲' WHERE name = 'Gazpacho' AND brand = 'Don Simon';
UPDATE public.foods SET icon = '🍲' WHERE name = 'Gazpacho' AND brand = 'Hacendado';
UPDATE public.foods SET icon = '🍮' WHERE name = 'Gelatina Frutos Rojos';
UPDATE public.foods SET icon = '🟢' WHERE name = 'Guisantes';
UPDATE public.foods SET icon = '🍦' WHERE name = 'Helado Proteico Brownie';
UPDATE public.foods SET icon = '🍦' WHERE name = 'Helado Sandwich de Nata 0';
UPDATE public.foods SET icon = '🫙' WHERE name = 'Ketchup 0';
UPDATE public.foods SET icon = '🥛' WHERE name = 'Leche';
UPDATE public.foods SET icon = '🍝' WHERE name = 'Macarrón';
UPDATE public.foods SET icon = '🌽' WHERE name = 'Maiz dulce';
UPDATE public.foods SET icon = '🥄' WHERE name = 'Mayonesa ligera';
UPDATE public.foods SET icon = '🍯' WHERE name = 'Miel de flores';
UPDATE public.foods SET icon = '🥫' WHERE name = 'Mostaza';
UPDATE public.foods SET icon = '🥜' WHERE name = 'Nocilla de Pistacho';
UPDATE public.foods SET icon = '🍞' WHERE name = 'Pan de maiz';
UPDATE public.foods SET icon = '🍞' WHERE name = 'Pan de molde integral' AND brand = 'Alipende';
UPDATE public.foods SET icon = '🍞' WHERE name = 'Pan de molde integral' AND brand = 'BM';
UPDATE public.foods SET icon = '🍞' WHERE name = 'Pan de molde integral grande';
UPDATE public.foods SET icon = '🍞' WHERE name = 'Pan de molde Maiz';
UPDATE public.foods SET icon = '🍞' WHERE name = 'Pan Masa Madre';
UPDATE public.foods SET icon = '🥘' WHERE name = 'Pasta de Lentejas';
UPDATE public.foods SET icon = '🍜' WHERE name = 'Pastilla de Caldo de Pollo';
UPDATE public.foods SET icon = '🍗' WHERE name = 'Pavo sin grasa';
UPDATE public.foods SET icon = '🧀' WHERE name = 'Quesito Light';
UPDATE public.foods SET icon = '🧀' WHERE name = 'Quesitos Light' AND brand = 'Alipende';
UPDATE public.foods SET icon = '🧀' WHERE name = 'Quesitos Light' AND brand = 'Dia';
UPDATE public.foods SET icon = '🧀' WHERE name = 'Queso cottage';
UPDATE public.foods SET icon = '🌶' WHERE name = 'Siracha';
UPDATE public.foods SET icon = '🍖' WHERE name = 'Taquitos de Jamon';
UPDATE public.foods SET icon = '🍞' WHERE name = 'Tiburon';
UPDATE public.foods SET icon = '🍅' WHERE name = 'Tomate frito';
UPDATE public.foods SET icon = '🍅' WHERE name = 'Tomate triturado';
UPDATE public.foods SET icon = '🍘' WHERE name = 'Tortitas de Maiz';
UPDATE public.foods SET icon = '🍘' WHERE name = 'Tortitas de trigo';
UPDATE public.foods SET icon = '💪' WHERE name = 'Whey Caramelo';
UPDATE public.foods SET icon = '💪' WHERE name = 'Whey Cereales';
UPDATE public.foods SET icon = '🥛' WHERE name = 'Yogur griego Ligero';
UPDATE public.foods SET icon = '🥛' WHERE name = 'Yogurt griego Ligero';
UPDATE public.foods SET icon = '🥛' WHERE name = 'Yogurt proteinas de stracciatella';
UPDATE public.foods SET icon = '🍦' WHERE name = 'Helado de pistacho';
UPDATE public.foods SET icon = '🌽' WHERE name = 'Maiz para palomitas';
